version: '3.8'

services:
    db: 
      image: mysql
      restart: always
      ports:
        - "3306:3306"
      environments: 
        MYSQL_ROOT_PASSWORD: rootroot
        MYSQL_DATABASE:   floodify
      volumes:
        - mysql-db:/var/lib/mysql  

    backend: 
      build: ./floodify_backend
      restart: always
      ports:
        - "8080:8080"
      environments:
        SPRING_DATASOURCE_URL : jdbc:mysql://db:3306/floodify
        SPRING_DATASOURCE_USERNAME: root
        SPRING_DATASOURCE_PASSWORD: rootroot

      depends_on:
        - db  
    frontend:
      build: ./
      restart: always 
      ports: 
        - "3000:3000"
      depends_on:
        - backend  

volumes:
    mysql-db: 