apiVersion: v1
kind: ConfigMap
metadata:
  name: db-config
  namespace: floodify
data:
  MYSQL_DATABASE: "floodify"
  SPRING_DATASOURCE_URL: "jdbc:mysql://mysql:3306/floodify"
  SPRING_DATASOURCE_USERNAME: "root"